tentpalace/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from tentpalace import settings
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
path('login', views.signin, name="login"),

                  path('logout', views.signout, name="logout"),
                  path('show', views.show_customers, name="home"),
                  path('search', views.customers_search, name="search"),
                  path('show/<int:id>', views.details, name="details"),
                  path('customers/delete/<int:customer_id>', views.delete_customer, name="delete"),
                  path('customers/update/<int:customer_id>', views.update_customer, name="update"),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# admin@gmail.com
# admin
# 1234

main_app/models.py
import os.path
import uuid

from django.db import models

# Create your models here.

def generate_unique_name(instance, filename):
    name = uuid.uuid4()
    ext = filename.split(".")[-1]
    full_filename = f"{name}.{ext}"
    # full_filename = "%s.%s" % (name, ext)  gives same result as line 11
    return os.path.join("customers", full_filename)


class Customer(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=25)
    profile_pic = models.ImageField(upload_to=generate_unique_name, null=True, default="students/default.png")
    created_at = models.DateTimeField(auto_now_add=True)  # updates time automatically
    updated_at = models.DateTimeField(auto_now=True)  # hapa inaonyesha last time it was updated on the database


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main_app/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from main_app.app_forms import CustomerForm, LoginForm
from main_app.models import Customer


# Create your views here.
@login_required  # decorators
@permission_required('main_app.add_student')
def customers(request):
    if request.method == "POST":
        form = CustomerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "User saved successfully")
            return redirect("home")
    else:
        form = CustomerForm()

    return render(request, "customers.html", {"form": form})


@login_required
@permission_required('main_app.view_customer')
def show_customers(request, ):
    data = Customer.objects.all()  # select * FROM customers
    paginator = Paginator(data, 10)
    page_number = request.GET.get("page")
    data = paginator.get_page(page_number)
    return render(request, "display.html", {"customers": data})


@login_required
def details(request, id):
    student = Customer.objects.get(pk=id)
    return render(request, "details.html", {"customer": student})


@login_required
@permission_required('main_app.delete_customer')  # <your app name>, <action>, <model>
def delete_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    customer.delete()
    messages.info(request, f"Student {customer.first_name} was deleted successfully")
    return redirect("show")


@login_required
def customers_search(request, ):
    search = request.GET["search"]
    data = Customer.objects.filter(Q(first_name__icontains=search)
                                  | Q(last_name__icontains=search)
                                  | Q(email__contains=search)
                                  )

    if search.isnumeric():
        score = int(search)
        data = Customer.objects.filter(kcpe_score=score)

        paginator = Paginator(data, 10)
        page_number = request.GET.get("page")
        data = paginator.get_page(page_number)

    return render(request, "display.html", {"customers": data})


# elastic search


@login_required
def update_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, f"Successfully updated customer {customer.first_name}")
            return redirect("details", customer_id)

    else:
        form = CustomerForm(instance=customer)
        return render(request, "update.html", {"form": form})


def signin(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, "Signed in successfully")
                return redirect('home')
        messages.error(request, "Invalid username or password")
        return render(request, "login.html", {"form": form})


def signout(request):
    messages.success(request, "You are logged out!")
    logout(request)
    return redirect('login')

# editor user 123456 will have all the powers
# desk one user 123456 oly see and edit but not delete a student
# hr user 123456 just see

# Groups of users; editor group, desk one group and hr group

templates/alert.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-success alert-dismissible">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/customers.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    {% include 'navbar.html' %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-5">
                   {% include 'alert.html' %}
                <form action="" method="post" class="shadow px-3 py-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-danger w-100">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
	Register Customer
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    Details For {{ customer.first_name | capfirst }}
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-6 text-center">
                {% include 'alert.html' %}
                {% if customer.profile_pic %}
                    <img src="{{ customer.profile_pic.url }}" class="img-fluid" alt="">
                {% endif %}
                <h3>{{ customer.first_name | capfirst }} {{ customer.last_name | capfirst }}</h3>
                <p>Added On {{ customer.created_at | naturaltime }}</p>


                {% if perms.main_app.delete_customer %}
                    <a href="{% url 'delete' customer.id %}" class="btn btn-danger w-50">Delete</a>
                {% endif %}

                {% if perms.main_app.change_customer %}
                    <a href="{% url 'update' customer.id %}" class="btn btn-danger">Update</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/display.html
{% extends 'base.html' %}
{% block title %}
    All Customers
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8">
            {% include 'alert.html' %}
                <table class="table">
                    <thead>
                    <tr>
                        <th>Names</th>
                        <th>Email</th>
                        <th>Phone</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customers %}
                        <tr>
                            <td>
                                <a href="{% url 'details' customer.id %}"
                                   class="text-decoration-none">{{ customer.first_name }} {{ customer.last_name }}</a>
                            </td>
                            <td>{{ customer.email }}</td>
                            <td>{{ customer.phone }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if customers.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href='?page={{ customer.previous_page_number }}'>Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href='' tabindex="-1" aria-disabled="True">Previous</a>
                            </li>
                        {% endif %}

                        {% if customer.has_next %}
                            <li class="page-item">
                                <a class="page-link" href='?page={{ customer.next_page_number }}'>Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href='' tabindex="-1" aria-disabled="True">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    Signin
{% endblock %}

{% block content %}
   <div class="vh-100 d-flex justify-content-center align-items-center">
       <div class="row justify-content-center w-100">
            <div class="col-sm-4">
                <form action="{% url 'login' %}" method="post" class="shadow px-3 py-4">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-dark rounded-0 w-100">Sign In</button>
                </form>
            </div>
       </div>
   </div>
{% endblock %}

templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Customer Portal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link  {% if '/' == request.path %} active {% endif %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if 'show' in request.path %} active {% endif %} " href="{% url 'home' %}">Customers Details</a>
                </li>

            </ul>
            <form class="d-flex" method="get" action="{% url 'search' %}">
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            <ul class="navbar-nav ms-3 mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">LOGOUT{{ user.first_name }}</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}">Link</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    {% include 'navbar.html' %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-5">
                   {% include 'alert.html' %}
                <form action="{{ request.path }}" method="post" class="shadow px-3 py-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-danger w-100">Update Customer</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
	Update Customer
{% endblock %}